template-file-path: pca-main.template
parameters:
  #--- Core Configuration ---
  AdminEmail: 'rspinabella@insurancenavy.com'
  AdminUsername: 'admin'
  Environment: 'PROD'
  
  #--- Features Enabled ---
  CallSummarization: 'BEDROCK'
  GenAIQuery: 'BEDROCK'
  EnablePcaDashboards: 'Yes'
  EnableGui: 'true'
  EnableTranscriptKendraSearch: 'Yes, create new Kendra Index (Developer Edition)'
  loadSampleAudioFiles: 'true'

  #--- Custom Settings ---
  ConversationLocation: 'America/Chicago'
  AllowedSignUpEmailDomain: 'insurancenavy.com'
  TranscribeLanguages: 'en-US | es-US | ar-AE'
  SpeakerSeparationType: 'channel'
  
  #--- Bedrock / LLM ---
  SummarizationBedrockModelId: 'us.amazon.nova-pro-v1:0'
  GenAIQueryBedrockModelId: 'us.amazon.nova-pro-v1:0'
  SummarizationLLMThirdPartyApiKey: '****'

  #--- Buckets & storage (Keeping these implicit/defaults is usually safer, but defining explicitly as requested) ---
  InputBucketRawAudio: 'originalAudio'
  InputBucketOrigTranscripts: 'originalTranscripts'
  InputBucketAudioPlayback: 'playbackAudio'
  InputBucketFailedTranscriptions: 'failedAudio'
  OutputBucketParsedResults: 'parsedFiles'
  OutputBucketTranscribeResults: 'transcribeResults'
  TelephonyCTRFileSuffix: '_metadata.json | _call_metadata.json'
  EntityStringMap: 'sample-entities.csv'